### ISSUE TITLE
SOPORTE-->Solicitud de planilla para carga masiva de herramientas de Pañol

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-pan#29]
Ambiente Producción - v2.3.10

**Descripción:**
El cliente solicita realizar la carga masiva de los registros de las herramientas y para ello, requiere cargar la planilla que se ajusta al listado en la base de datos. Favor de presentarla en el ticket y dirigirla a Facundo.

**Comment by jfernandez-trazalog** [comment]
Rodo Ruiz.

**Comment by jfernandez-trazalog** [comment]
Rodo Ruiz.

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.2
